// Generated by scripts/sync-colors.py. Do not edit.
import 'package:flutter/material.dart';

abstract final class NBColors {
  static const page = Color(0xFFF5F5F7);
  static const surface = Color(0xFFFFFFFF);
  static const pressed = Color(0xFFECECEF);
  static const ink = Color(0xFF1D1D1F);
  static const secondary = Color(0xFF48484D);
  static const muted = Color(0xFF6E6E73);
  static const line = Color(0xFFE5E5EA);
  static const control = Color(0xFF8A8A8F);
  static const link = Color(0xFF526477);
  static const activeSurface = Color(0xFFEEF1F5);
  static const action = Color(0xFF1D1D1F);
  static const actionPressed = Color(0xFF343438);
  static const inverse = Color(0xFFFFFFFF);
}
