"""Generate platform color primitives from the one reviewed palette."""
from pathlib import Path
import json, re, sys
root=Path(__file__).resolve().parents[1]
colors=json.loads((root/'design-system/nailbook/colors.json').read_text())
check='--check' in sys.argv
failed=[]
def emit(path,body):
 p=root/path
 if check:
  if not p.exists() or p.read_text()!=body: failed.append(path)
 else:
  p.parent.mkdir(parents=True,exist_ok=True);p.write_text(body)
def kebab(s): return re.sub(r'[A-Z]',lambda m:'-'+m[0].lower(),s)
css='/* Generated by scripts/sync-colors.py. Do not edit. */\n'
props=''.join(f'  --nb-{kebab(k)}: {v};\n  --nb-{kebab(k)}-rgb: '+', '.join(str(int(v[i:i+2],16)) for i in [1,3,5])+';\n' for k,v in colors.items())
for scope in ['technician-frontend','client-frontend','admin-frontend','landing-frontend','website']:
 emit(scope+'/src/colors.generated.css',css+':root {\n'+props+'}\n')
 emit(scope+'/src/colors.generated.ts','// Generated by scripts/sync-colors.py. Do not edit.\nexport const colors = '+json.dumps(colors,indent=2)+' as const;\n')
emit('client-wxapp/styles/colors.generated.wxss',css+'page {\n'+props+'}\n')
semantic=json.loads((root/'design-system/nailbook/miniprogram-semantics.json').read_text())
semantic_props=''.join(f'  --nb-{kebab(k)}: {v};\n' for k,v in semantic.items())
emit('client-wxapp/styles/semantics.generated.wxss',css+'page {\n'+semantic_props+'}\n')
# Isolated components reject page selectors; scope the same primitives and aliases to their root class.
aliases=(root/'client-wxapp/styles/tokens.wxss').read_text().split('page {',1)[1].rsplit('}',1)[0]
emit('client-wxapp/styles/component-tokens.generated.wxss',css+'.nb-theme {\n'+props+semantic_props+aliases+'}\n')
emit('client-wxapp/utils/colors.js','// Generated by scripts/sync-colors.py. Do not edit.\nmodule.exports = '+json.dumps({**colors,**semantic},indent=2)+';\n')
# Platform configuration does not evaluate CSS variables.
config_path='client-wxapp/app.json'
config=(root/config_path).read_text()
for field,role in [('navigationBarBackgroundColor','surface'),('backgroundColor','page')]:
 config=re.sub(r'("'+field+r'"\s*:\s*")[^"]+',lambda m:m[1]+colors[role],config)
emit(config_path,config)
accent_path='ios/NailBook/Resources/Assets.xcassets/AccentColor.colorset/Contents.json'
accent=json.loads((root/accent_path).read_text())
for entry in accent['colors']:
 entry['color']={'color-space':'srgb','components':{'red':'0x1D','green':'0x1D','blue':'0x1F','alpha':'1.000'}}
 # Keep the asset in sync if the action color is deliberately changed.
 for channel,start in [('red',1),('green',3),('blue',5)]:
  entry['color']['components'][channel]='0x'+colors['action'][start:start+2]
emit(accent_path,json.dumps(accent,indent=2)+'\n')
# External SVG images cannot inherit page currentColor. Sync their three states.
for icon in (root/'client-wxapp/static/icons').glob('*.svg'):
 if icon.name == 'wechat.svg': continue  # Official third-party mark.
 source=icon.read_text()
 inverse=any(x in icon.stem for x in ['-white','-light'])
 selected=icon.stem.endswith('-active')
 def icon_color(m):
  attr,value=m[1],m[2]
  if icon.stem=='check-circle': value=semantic['success']
  elif icon.stem in ['social-heart-active', 'social-like-active']: value=semantic['like']
  elif icon.stem=='social-star-active': value=semantic['favorite']
  elif icon.stem=='status-pin': value=semantic['workPinned']
  elif icon.stem=='status-featured': value=semantic['workFeatured']
  elif icon.stem=='notification-service': value=semantic['success'] if attr=='stroke' else semantic['successSurface']
  elif icon.stem=='notification-system': value=colors['muted'] if attr=='stroke' else colors['page']
  elif icon.stem in ['tab-home-active', 'tab-calendar-active', 'tab-compass-active', 'tab-chat-active', 'tab-profile-active', 'tab-customers-active']: value=semantic['textLink']
  elif selected and icon.stem.startswith('tab-'): value=semantic['textLink'] if attr=='stroke' else semantic['softSurface']
  elif inverse: value=colors['inverse']
  elif selected: value=colors['ink'] if attr=='stroke' or value.upper()==colors['ink'] else colors['page']
  else: value=colors['muted']
  return attr+'="'+value+'"'
 body=re.sub(r'(stroke|fill)="(#[0-9a-fA-F]{3,8})"',icon_color,source)
 if selected and icon.stem.startswith('tab-'):
  body=re.sub(r'stroke-width="[^"]+"', 'stroke-width="2.4"', body)
 emit(str(icon.relative_to(root)),body)
emit('mobile-flutter/lib/core/theme/colors.generated.dart',"// Generated by scripts/sync-colors.py. Do not edit.\nimport 'package:flutter/material.dart';\n\nabstract final class NBColors {\n"+''.join(f'  static const {k} = Color(0xFF{v[1:]});\n' for k,v in colors.items())+'}\n')
# Embed in an existing Xcode source so file-membership changes are unnecessary.
p=root/'ios/NailBook/Core/DesignSystem/Colors.swift'
marker='// BEGIN GENERATED COLOR PRIMITIVES'
base=p.read_text().split(marker)[0].rstrip()+'\n\n'
body=marker+' — scripts/sync-colors.py\nenum NBColors {\n'+''.join(f'    static let {k} = Color(hex: "{v[1:]}")\n' for k,v in colors.items())+'}\n'
if check:
 if p.read_text()!=base+body: failed.append(str(p.relative_to(root)))
else:p.write_text(base+body)
if failed:
 print('Color outputs out of sync:',*failed,sep='\n');sys.exit(1)
print('Color outputs in sync' if check else 'Generated color primitives for 8 surfaces')
