// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4QNxNUdXNRC_qL7yk_pZHKKDmakRQ_QM',
    appId: '1:663393249269:android:0c7aa0c2afbebd35dce2bc',
    messagingSenderId: '663393249269',
    projectId: 'applied-mystery-316003',
    databaseURL: 'https://applied-mystery-316003-default-rtdb.firebaseio.com',
    storageBucket: 'applied-mystery-316003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovkDHgcpQvHwjY3uwfwawV6rgPAM-0Mk',
    appId: '1:663393249269:ios:36b95c35f7864ca2dce2bc',
    messagingSenderId: '663393249269',
    projectId: 'applied-mystery-316003',
    databaseURL: 'https://applied-mystery-316003-default-rtdb.firebaseio.com',
    storageBucket: 'applied-mystery-316003.firebasestorage.app',
    iosBundleId: 'com.nailbook.nailbookMobile',
  );
}
